# Generated by Django 2.1.1 on 2018-11-17 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeManage',
            fields=[
                ('tradeMgtNo', models.IntegerField(primary_key=True, serialize=False, verbose_name='取引管理番号')),
                ('coinType', models.CharField(choices=[(1, 'ビットコイン')], max_length=3, verbose_name='通貨種別')),
                ('tradeStatus', models.CharField(choices=[(1, '注文中'), (2, '約定済'), (3, '反対売買成立'), (4, '取消')], max_length=3, verbose_name='取引ステータス')),
                ('orderDate', models.CharField(max_length=8, verbose_name='注文日')),
                ('orderTime', models.CharField(max_length=12, verbose_name='注文時刻')),
                ('finishDate', models.CharField(max_length=8, verbose_name='完了日')),
                ('finishTime', models.CharField(max_length=12, verbose_name='完了時刻')),
                ('amount', models.FloatField(verbose_name='単位数')),
                ('orderPrice', models.FloatField(verbose_name='注文価格')),
                ('contractPrice', models.FloatField(verbose_name='約定価格')),
            ],
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coinType', models.CharField(choices=[(1, 'ビットコイン')], max_length=3, verbose_name='通貨種別')),
                ('amount', models.FloatField(verbose_name='単位数')),
                ('unitPrice', models.FloatField(verbose_name='終値')),
            ],
        ),
        migrations.CreateModel(
            name='UserBalanceManage',
            fields=[
                ('balanceMgtNo', models.IntegerField(primary_key=True, serialize=False, verbose_name='残高管理番号')),
                ('registerDate', models.CharField(max_length=8, verbose_name='登録日')),
                ('registerTime', models.CharField(max_length=12, verbose_name='登録時刻')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=50, verbose_name='ユーザID')),
                ('exchangeCode', models.CharField(choices=[(1, 'bit_flyer'), (2, 'zaif')], max_length=3, verbose_name='取引所コード')),
            ],
        ),
        migrations.AddField(
            model_name='userbalancemanage',
            name='userInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trade.UserInfo', verbose_name='ユーザ情報'),
        ),
        migrations.AddField(
            model_name='userbalance',
            name='UserBalanceManage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trade.UserBalanceManage', verbose_name='ユーザ残高情報'),
        ),
        migrations.AddField(
            model_name='trademanage',
            name='userInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trade.UserInfo', verbose_name='ユーザ情報'),
        ),
    ]
