# Generated by Django 2.1.1 on 2018-12-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademanage',
            name='coinType',
            field=models.CharField(choices=[('BIT_COIN', 'ビットコイン')], max_length=3, verbose_name='通貨種別'),
        ),
        migrations.AlterField(
            model_name='trademanage',
            name='tradeStatus',
            field=models.CharField(choices=[('ORDER', '注文中'), ('CONTRACT', '約定済'), ('FINISH', '反対売買成立'), ('CANCEL', '取消')], max_length=3, verbose_name='取引ステータス'),
        ),
        migrations.AlterField(
            model_name='userbalance',
            name='coinType',
            field=models.CharField(choices=[('BIT_COIN', 'ビットコイン')], max_length=3, verbose_name='通貨種別'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='exchangeCode',
            field=models.CharField(choices=[('BIT_FLYER', 'ビットフライヤー'), ('ZAIF', 'ザイフ')], max_length=10, verbose_name='取引所コード'),
        ),
    ]
