# Generated by Django 2.1.1 on 2018-12-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20181209_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademanage',
            name='coinType',
            field=models.CharField(choices=[('BIT_COIN', 'ビットコイン')], max_length=10, verbose_name='通貨種別'),
        ),
    ]
