# Generated by Django 2.1.1 on 2018-12-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20181209_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademanage',
            name='tradeStatus',
            field=models.CharField(choices=[('ORDER', '注文中'), ('CONTRACT', '約定済'), ('FINISH', '反対売買成立'), ('CANCEL', '取消')], max_length=10, verbose_name='取引ステータス'),
        ),
    ]
