# Generated by Django 2.1.4 on 2018-12-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20181209_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbalance',
            old_name='UserBalanceManage',
            new_name='userBalanceManage',
        ),
        migrations.AlterField(
            model_name='trademanage',
            name='coinType',
            field=models.CharField(choices=[('BTC_JPY', 'ビットコイン'), ('FX_BTC_JPY', 'FXビットコイン')], max_length=10, verbose_name='通貨種別'),
        ),
        migrations.AlterField(
            model_name='userbalance',
            name='coinType',
            field=models.CharField(choices=[('BTC_JPY', 'ビットコイン'), ('FX_BTC_JPY', 'FXビットコイン')], max_length=3, verbose_name='通貨種別'),
        ),
    ]
